### ISSUE TITLE
Cannot install or start Jellyfin 10.9.3

### ISSUE THREAD

**Issue by alanman87** [jellyfin/jellyfin-plugin-transcodekiller#5]
Cannot install or start version 10.9.3 due to the following error:

```
[13:08:59] [ERR] [17] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://raw.githubusercontent.com/crobibero/jellyfin-plugin-transcodekiller/master/manifest.json
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<FromJsonAsyncCore>g__Core|12_0[TValue,TJsonOptions](HttpClient client, Task`1 responseTask, Boolean usingResponseHeadersRead, CancellationTokenSource linkedCTS, Func`4 deserializeMethod, TJsonOptions jsonOptions, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifestName, String manifest, Boolean filterIncompatible, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
This plugins is now in the official repo.

**Comment by alanman87** [comment]
How do I fix it? This change broke my instance

**Comment by crobibero** [comment]
Just remove the old plugin repo. If you can't access the web page you can remove the lines from system.xml
